apiVersion: v1
kind: Service
metadata:
  name: contoso-app
  namespace: contoso-devsecops
spec:
  type: LoadBalancer
  selector:
    app: contoso-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
